# Generated by Django 4.2.3 on 2023-08-14 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('name_owner', models.CharField(max_length=64)),
                ('parag1', models.TextField()),
                ('parag2', models.TextField()),
                ('number1', models.TextField()),
                ('number2', models.TextField()),
            ],
        ),
    ]
