# Generated by Django 4.2.3 on 2023-08-14 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.ImageField(upload_to='')),
                ('name1', models.CharField(max_length=64)),
                ('parag1', models.TextField()),
                ('img2', models.ImageField(upload_to='')),
                ('name2', models.CharField(max_length=64)),
                ('parag12', models.TextField()),
                ('img3', models.ImageField(upload_to='')),
                ('name3', models.CharField(max_length=64)),
                ('parag3', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='about',
            name='parag2',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='number1',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='number2',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='parag1',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='parag2',
            field=models.TextField(blank=True),
        ),
    ]
