# Generated by Django 4.2.3 on 2023-08-14 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_home_alter_about_parag2_alter_contact_number1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='img1',
            new_name='imgone',
        ),
        migrations.RenameField(
            model_name='home',
            old_name='img2',
            new_name='imgthree',
        ),
        migrations.RenameField(
            model_name='home',
            old_name='img3',
            new_name='imgtwo',
        ),
        migrations.RenameField(
            model_name='home',
            old_name='name1',
            new_name='nameone',
        ),
        migrations.RenameField(
            model_name='home',
            old_name='name2',
            new_name='namethree',
        ),
        migrations.RenameField(
            model_name='home',
            old_name='name3',
            new_name='nametwo',
        ),
        migrations.RenameField(
            model_name='home',
            old_name='parag1',
            new_name='paragone',
        ),
        migrations.RenameField(
            model_name='home',
            old_name='parag12',
            new_name='paragthree',
        ),
        migrations.RenameField(
            model_name='home',
            old_name='parag3',
            new_name='paragtwo',
        ),
    ]
