# Generated by Django 4.2.3 on 2023-08-21 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_cars_img1_cars_img2_cars_img3_cars_img4_cars_img5_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='img6',
            field=models.ImageField(blank=True, upload_to='home/files/covers'),
        ),
    ]
